version: '3.1'
services:

    # The Application
    app:
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        container_name: docker-mochilo-app
        working_dir: /var/www/application
        volumes:
            - .:/var/www/application
            - ./docker/php.ini.override.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - PHP_IDE_CONFIG=serverName=docker

    # The Web Server
    web:
        image: nginx:1.10
        container_name: docker-mochilo-app-webserver
        working_dir: /var/www/application
        volumes:
            - .:/var/www/application
            - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80